#!/bin/sh
#
# @name LEVITUM P2
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_
ULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=p2}

param set-default SIM_GZ_EN 1
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 2

param set-default COM_PREARM_MODE 2

param set-default CA_ROTOR_COUNT 7
param set-default CA_ROTOR0_PX -0.203
param set-default CA_ROTOR0_PY 0.436
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.203
param set-default CA_ROTOR1_PY -0.436
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX 0.571
param set-default CA_ROTOR2_PY -0.640
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX -0.683
param set-default CA_ROTOR3_PY 0.436
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR4_PX 0.571
param set-default CA_ROTOR4_PY 0.640
param set-default CA_ROTOR4_KM -0.05
param set-default CA_ROTOR5_PX -0.683
param set-default CA_ROTOR5_PY -0.436
param set-default CA_ROTOR5_KM 0.05
param set-default CA_ROTOR6_AX 1.0
param set-default CA_ROTOR6_AZ 0.0
param set-default CA_ROTOR6_PX 0.2

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 10
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_MIN6 10

param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_MIN7 0

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

param set-default SIM_GZ_SV_REV 3

param set-default SIM_GZ_HOME_LAT 48.28035
param set-default SIM_GZ_HOME_LON 11.71989


param set-default COM_RC_IN_MODE 1
param set-default ASPD_PRIMARY 1

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 3
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 3
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 5
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS3_TYPE 6
param set-default CA_SV_CS3_TRQ_P 1.0

# param set-default FW_L1_PERIOD 12
# TODO: configure fixedwing
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_R_RMAX 30.5
#param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

param set-default MC_AIRMODE 1
param set-default MC_ROLLRATE_P 1.15
param set-default MC_ROLLRATE_I 0.42
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_K 0.8
param set-default MC_PITCHRATE_P 1.45
param set-default MC_PITCHRATE_I 0.12
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_K 0.85
param set-default MC_YAWRATE_P 0.45
param set-default MC_YAWRATE_I 0.2
param set-default MC_YAWRATE_D 0.2
param set-default MC_YAWRATE_K 2.1
param set-default MC_ROLL_P 4.0
param set-default MC_PITCH_P 2.5
param set-default MC_YAW_P 3.7

param set-default MIS_TAKEOFF_ALT 10

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_XY_P 0.4
param set-default MPC_XY_VEL_P_ACC 3.6
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1
param set-default MPC_Z_VEL_I_ACC 1.5
param set-default MPC_Z_VEL_P_ACC 8.0

param set-default NAV_ACC_RAD 5

param set-default VT_FWD_THRUST_EN 4
# param set-default VT_F_TRANS_THR 0.75
param set-default VT_ARSP_TRANS 15
param set-default VT_F_TRANS_DUR 20
param set-default VT_B_TRANS_DUR 30
param set-default VT_TYPE 2
param set-default FD_ESCS_EN 0
