uint64 timestamp					# time since system start (microseconds)

float32 stack_voltage
float32 load_current
float32 power
float32 energy
float32 battery_voltage
float32 battery_current
float32 load_voltage
float32 stack_temp_sensor_1
float32 stack_temp_sensor_2
float32 stack_temp_sensor_3
float32 stack_temp_sensor_4
float32 target_stack_temp
float32 board_temp
float32 h2_storage_supply_pressure
float32 fan_speed

uint8 operation_state
