#!/bin/sh
#
# @name Generic Standard VTOL
#
# @type Standard VTOL
# @class VTOL

# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
# @board holybro_kakutef7 exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default CA_AIRFRAME 2
param set-default CA_ROTOR_COUNT 7
#param set-default CA_ROTOR4_AX 1
#param set-default CA_ROTOR4_AZ 0
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS3_TRQ_Y 1
param set-default CA_SV_CS3_TYPE 4
param set-default VT_TYPE 2
param set-default MAV_TYPE 22

# Square quadrotor X PX4 numbering


# Lift rotors (hex layout)
param set-default CA_ROTOR0_PX 1.0
param set-default CA_ROTOR0_PY 0.0
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX 0.5
param set-default CA_ROTOR1_PY 0.866
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX -0.5
param set-default CA_ROTOR2_PY 0.866
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX -1.0
param set-default CA_ROTOR3_PY 0.0
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR4_PX -0.5
param set-default CA_ROTOR4_PY -0.866
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR5_PX 0.5
param set-default CA_ROTOR5_PY -0.866
param set-default CA_ROTOR5_KM -0.05


# Pusher motor
param set-default CA_ROTOR6_AX 1.0
param set-default CA_ROTOR6_AZ 0.0
param set-default CA_ROTOR6_PX -1.0
